<h1>Toronto Neighborhood Project</h1>

Import necessary libraries/modules

In [30]:
import requests
import bs4
import pandas as pd
import numpy as np

Get and process data from the web

In [48]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
page = requests.get(url).text
page_bs = bs4.BeautifulSoup(page)
table = page_bs.select("table")
rows = table[0].select("tr")[1:]

Process data with beautiful soup and create dataframe object

In [49]:
data = []
for row in rows:
    td = row.select('td')
    if td[1].text != "Not assigned\n":
        postCode = td[0].text.strip()
        borough = td[1].text.strip()
        neighborhood = td[2].text.strip()
        
        if neighborhood == "Not assigned":
            neighborhood = borough
            
        new_row = [postCode, borough, neighborhood]
        data.append(new_row)
df = pd.DataFrame(data)
df.columns=['PostalCode','Borough','Neighborhood']

Get latitude / longitude data

In [93]:
geo_data = pd.read_csv("Geospatial_Coordinates.csv")

latitudes = []
longitudes = []

for row in range(len(df)):
    latitudes.append(geo_data[geo_data['Postal Code'] == df.iloc[row].PostalCode].Latitude.value)
    longitudes.append(geo_data[geo_data['Postal Code'] == df.iloc[row].PostalCode].Longitude.value)

df['Latitudes'] = latitudes
df['Longitudes'] = longitudes

AttributeError: 'Series' object has no attribute 'value'

In [94]:
df

,PostalCode,Borough,Neighborhood,test,Latitudes,Longitudes
0,test,North York,Parkwoods,0,"Series([], Name: Latitude, dtype: float64)","Series([], Name: Longitude, dtype: float64)"
1,M4A,North York,Victoria Village,0,"34 43.725882 Name: Latitude, dtype: float64","34 -79.315572 Name: Longitude, dtype: float64"
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",0,"53 43.65426 Name: Latitude, dtype: float64","53 -79.360636 Name: Longitude, dtype: float64"
3,M6A,North York,"Lawrence Manor, Lawrence Heights",0,"71 43.718518 Name: Latitude, dtype: float64","71 -79.464763 Name: Longitude, dtype: float64"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",0,"85 43.662301 Name: Latitude, dtype: float64","85 -79.389494 Name: Longitude, dtype: float64"
...,...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",0,"90 43.653654 Name: Latitude, dtype: float64","90 -79.506944 Name: Longitude, dtype: float64"
99,M4Y,Downtown Toronto,Church and Wellesley,0,"52 43.66586 Name: Latitude, dtype: float64","52 -79.38316 Name: Longitude, dtype: float64"
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",0,"87 43.662744 Name: Latitude, dtype: float64","87 -79.321558 Name: Longitude, dtype: float64"
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",0,"91 43.636258 Name: Latitude, dtype: float64","91 -79.498509 Name: Longitude, dtype: float64"
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",0,"92 43.628841 Name: Latitude, dtype: float64","92 -79.520999 Name: Longitude, dtype: float64"

In [64]:
df.iloc[0].test = 0

In [71]:
df['test'] = 0

In [75]:

df.iloc[0].test = 100

In [37]:
df.iloc[0].PostalCode =  "test"

In [83]:
df.iloc[1].test = 'test'

/home/ken/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [82]:
df

,PostalCode,Borough,Neighborhood,test
0,test,North York,Parkwoods,0
1,M4A,North York,Victoria Village,0
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",0
3,M6A,North York,"Lawrence Manor, Lawrence Heights",0
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",0
...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",0
99,M4Y,Downtown Toronto,Church and Wellesley,0
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",0
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",0
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",0